services:
  sulu-php:
    build:
      context: .
      dockerfile: ./docker/local/php/Dockerfile
    container_name: sulu_php
    volumes:
      - ./:/var/www/html       # Mount Sulu project directory
      - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini  # Mount custom php.ini
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    working_dir: /var/www/html
    depends_on:
      - sulu-mariadb

  sulu-mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    container_name: sulu_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sulu
      MYSQL_USER: sulu
      MYSQL_PASSWORD: sulu
    volumes:
      - db_data:/var/lib/mysql

  sulu-nginx:
    image: nginx:latest
    container_name: sulu_nginx
    volumes:
      - ./docker/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
      - ./:/var/www/html       # Mount Sulu project directory
    ports:
      - "80:80"
    depends_on:
      - sulu-php

volumes:
  db_data:
